"""Initial catalog schema.

Hand-maintained rather than autogenerated for one reason: Alembic's autogenerate does not emit
DROP TYPE for native Postgres enums, so a downgrade leaves the types behind and the next
upgrade fails with "type already exists". Creating and dropping them explicitly makes the
migration reversible, which is what makes it safe to test.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SUBJECT_DOMAIN = (
    "llm_model",
    "operating_system",
    "database",
    "messaging_queue",
    "saas_platform",
    "language_runtime",
    "repo_library",
)
BUG_TYPE = (
    "security",
    "functional",
    "performance",
    "compatibility",
    "breaking_change",
    "deprecation",
    "build",
)
RECORD_ORIGIN = ("crawled", "scan_derived", "eval_derived")
LIFECYCLE_STATE = (
    "candidate",
    "active",
    "fixed",
    "disputed",
    "retracted",
    "superseded",
)
JOB_TYPE = ("noop", "crawl", "extract", "scan_fetch", "scan_analyze")
JOB_STATE = ("queued", "running", "succeeded", "failed", "budget_exceeded")

_ENUMS = {
    "subject_domain": SUBJECT_DOMAIN,
    "bug_type": BUG_TYPE,
    "record_origin": RECORD_ORIGIN,
    "lifecycle_state": LIFECYCLE_STATE,
    "job_type": JOB_TYPE,
    "job_state": JOB_STATE,
}


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(*_ENUMS[name], name=name, create_type=False)


def upgrade() -> None:
    for name, values in _ENUMS.items():
        postgresql.ENUM(*values, name=name).create(op.get_bind(), checkfirst=True)

    op.create_table(
        "component",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject_domain", _enum("subject_domain"), nullable=False),
        sa.Column("canonical_ref", sa.String(length=200), nullable=False),
        sa.Column("ecosystem", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component")),
        sa.UniqueConstraint("subject_domain", "canonical_ref", name="component_identity"),
    )
    op.create_table(
        "component_alias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
            name=op.f("fk_component_alias_component_id_component"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_alias")),
        sa.UniqueConstraint("alias", name="alias_is_unambiguous"),
    )
    op.create_table(
        "bug_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("subject_domain", _enum("subject_domain"), nullable=False),
        sa.Column("bug_type", _enum("bug_type"), nullable=False),
        sa.Column("applicability", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("origin", _enum("record_origin"), nullable=False),
        sa.Column("lifecycle_state", _enum("lifecycle_state"), nullable=False),
        sa.Column("superseded_by_id", sa.Uuid(), nullable=True),
        sa.Column("identity_key", sa.String(length=300), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"], ["component.id"], name=op.f("fk_bug_record_component_id_component")
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["bug_record.id"],
            name=op.f("fk_bug_record_superseded_by_id_bug_record"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bug_record")),
    )
    op.create_index("ix_bug_record_retrieval", "bug_record", ["subject_domain", "component_id"])
    op.create_index("ix_bug_record_state", "bug_record", ["lifecycle_state"])
    op.create_index(op.f("ix_bug_record_identity_key"), "bug_record", ["identity_key"])

    op.create_table(
        "bug_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence_url", sa.Text(), nullable=True),
        sa.Column("raw_artifact_uri", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["bug_record.id"],
            name=op.f("fk_bug_version_record_id_bug_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bug_version")),
        sa.UniqueConstraint("record_id", "version_no", name="version_sequence"),
        sa.UniqueConstraint("record_id", "content_hash", name="dedup_by_content"),
    )
    op.create_index("ix_bug_version_observed", "bug_version", ["observed_at"])

    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", _enum("job_type"), nullable=False),
        sa.Column("state", _enum("job_state"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("budget_tokens", sa.Integer(), nullable=True),
        sa.Column("spent_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index("ix_job_type_state", "job", ["job_type", "state"])
    op.create_index("ix_job_created", "job", ["created_at"])
    op.create_index(op.f("ix_job_tenant_id"), "job", ["tenant_id"])

    op.create_table(
        "scan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("repo_ref", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=100), nullable=True),
        sa.Column("grounding_complete", sa.Boolean(), nullable=False),
        sa.Column("uncovered_components", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], name=op.f("fk_scan_job_id_job")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan")),
    )
    op.create_index(op.f("ix_scan_tenant_id"), "scan", ["tenant_id"])

    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("bug_type", _enum("bug_type"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("reachable", sa.Boolean(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("version_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"], ["component.id"], name=op.f("fk_finding_component_id_component")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scan.id"], name=op.f("fk_finding_scan_id_scan"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
    )
    op.create_index("ix_finding_scan", "finding", ["scan_id"])

    op.create_table(
        "finding_citation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("bug_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bug_version_id"],
            ["bug_version.id"],
            name=op.f("fk_finding_citation_bug_version_id_bug_version"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_finding_citation_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_citation")),
        sa.UniqueConstraint("finding_id", "bug_version_id", name="citation_is_distinct"),
    )


def downgrade() -> None:
    op.drop_table("finding_citation")
    op.drop_table("finding")
    op.drop_table("scan")
    op.drop_table("job")
    op.drop_table("bug_version")
    op.drop_table("bug_record")
    op.drop_table("component_alias")
    op.drop_table("component")
    for name in _ENUMS:
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
