"""initial schema

Revision ID: 193520770f00
Revises:
Create Date: 2026-08-22 19:10:02.064384
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Autogenerate creates these inline with the tables but emits no DROP TYPE, so a downgrade
# leaves them behind and the next upgrade fails with "type already exists". Dropping them
# explicitly is what makes the migration reversible, and therefore testable.
_ENUM_TYPES = [
    "subject_domain",
    "bug_type",
    "privacy_scope",
    "principal_kind",
    "role",
    "record_origin",
    "lifecycle_state",
    "job_type",
    "job_state",
]

# RLS here is the data-layer half of NFR-19's isolation. Application filtering is one
# forgotten WHERE clause from a cross-tenant read, and that bug returns *more* data rather
# than an error, so it does not announce itself.
_TENANT_TABLES = ["team", "membership", "invite", "api_key", "job", "scan"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_app_user_external_subject")),
    )
    op.create_table(
        "component",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_domain",
            postgresql.ENUM(
                "llm_model",
                "operating_system",
                "database",
                "messaging_queue",
                "saas_platform",
                "language_runtime",
                "repo_library",
                name="subject_domain",
            ),
            nullable=False,
        ),
        sa.Column("canonical_ref", sa.String(length=200), nullable=False),
        sa.Column("ecosystem", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component")),
        sa.UniqueConstraint("subject_domain", "canonical_ref", name="component_identity"),
    )
    op.create_table(
        "tenant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenant_slug")),
    )
    op.create_table(
        "bug_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_domain",
            postgresql.ENUM(
                "llm_model",
                "operating_system",
                "database",
                "messaging_queue",
                "saas_platform",
                "language_runtime",
                "repo_library",
                name="subject_domain",
            ),
            nullable=False,
        ),
        sa.Column(
            "bug_type",
            postgresql.ENUM(
                "security",
                "functional",
                "performance",
                "compatibility",
                "breaking_change",
                "deprecation",
                "build",
                name="bug_type",
            ),
            nullable=False,
        ),
        sa.Column("applicability", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "origin",
            postgresql.ENUM("crawled", "scan_derived", "eval_derived", name="record_origin"),
            nullable=False,
        ),
        sa.Column(
            "privacy_scope",
            postgresql.ENUM("public", "subscriber", "tenant", name="privacy_scope"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "lifecycle_state",
            postgresql.ENUM(
                "candidate",
                "active",
                "fixed",
                "disputed",
                "retracted",
                "superseded",
                name="lifecycle_state",
            ),
            nullable=False,
        ),
        sa.Column("superseded_by_id", sa.Uuid(), nullable=True),
        sa.Column("identity_key", sa.String(length=300), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(privacy_scope = 'tenant') = (tenant_id IS NOT NULL)",
            name=op.f("ck_bug_record_tenant_scope_requires_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"], ["component.id"], name=op.f("fk_bug_record_component_id_component")
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["bug_record.id"],
            name=op.f("fk_bug_record_superseded_by_id_bug_record"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_bug_record_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bug_record")),
    )
    op.create_index(
        op.f("ix_bug_record_identity_key"), "bug_record", ["identity_key"], unique=False
    )
    op.create_index(
        "ix_bug_record_retrieval", "bug_record", ["subject_domain", "component_id"], unique=False
    )
    op.create_index(
        "ix_bug_record_scope", "bug_record", ["privacy_scope", "tenant_id"], unique=False
    )
    op.create_index("ix_bug_record_state", "bug_record", ["lifecycle_state"], unique=False)
    op.create_table(
        "component_alias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["component.id"],
            name=op.f("fk_component_alias_component_id_component"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_component_alias")),
        sa.UniqueConstraint("alias", name="alias_is_unambiguous"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "job_type",
            postgresql.ENUM(
                "noop", "crawl", "extract", "scan_fetch", "scan_analyze", name="job_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            postgresql.ENUM(
                "queued", "running", "succeeded", "failed", "budget_exceeded", name="job_state"
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("budget_tokens", sa.Integer(), nullable=True),
        sa.Column("spent_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_job_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index("ix_job_created", "job", ["created_at"], unique=False)
    op.create_index(op.f("ix_job_tenant_id"), "job", ["tenant_id"], unique=False)
    op.create_index("ix_job_type_state", "job", ["job_type", "state"], unique=False)
    op.create_table(
        "team",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_team_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
        sa.UniqueConstraint("tenant_id", "name", name="team_name_per_tenant"),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "principal_kind", postgresql.ENUM("user", "team", name="principal_kind"), nullable=False
        ),
        sa.Column("principal_user_id", sa.Uuid(), nullable=True),
        sa.Column("principal_team_id", sa.Uuid(), nullable=True),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("secret_hash", sa.LargeBinary(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["principal_team_id"], ["team.id"], name=op.f("fk_api_key_principal_team_id_team")
        ),
        sa.ForeignKeyConstraint(
            ["principal_user_id"],
            ["app_user.id"],
            name=op.f("fk_api_key_principal_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_api_key_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_key_prefix")),
    )
    op.create_index("ix_api_key_tenant", "api_key", ["tenant_id"], unique=False)
    op.create_table(
        "bug_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("evidence_url", sa.Text(), nullable=True),
        sa.Column("raw_artifact_uri", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["bug_record.id"],
            name=op.f("fk_bug_version_record_id_bug_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bug_version")),
        sa.UniqueConstraint("record_id", "content_hash", name="dedup_by_content"),
        sa.UniqueConstraint("record_id", "version_no", name="version_sequence"),
    )
    op.create_index("ix_bug_version_observed", "bug_version", ["observed_at"], unique=False)
    op.create_table(
        "invite",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", postgresql.ENUM("member", "tenant_admin", name="role"), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["app_user.id"],
            name=op.f("fk_invite_invited_by_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_invite_team_id_team"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_invite_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invite")),
    )
    op.create_index("ix_invite_tenant_email", "invite", ["tenant_id", "email"], unique=False)
    op.create_index("ix_invite_token", "invite", ["token_hash"], unique=False)
    op.create_table(
        "membership",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("role", postgresql.ENUM("member", "tenant_admin", name="role"), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_membership_team_id_team"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_membership_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_membership_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership")),
        sa.UniqueConstraint("tenant_id", "user_id", name="one_membership_per_tenant"),
    )
    op.create_index("ix_membership_user", "membership", ["user_id"], unique=False)
    op.create_table(
        "scan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("repo_ref", sa.Text(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("grounding_complete", sa.Boolean(), nullable=False),
        sa.Column("uncovered_components", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.id"], name=op.f("fk_scan_job_id_job")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_scan_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan")),
    )
    op.create_index(op.f("ix_scan_tenant_id"), "scan", ["tenant_id"], unique=False)
    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bug_type",
            postgresql.ENUM(
                "security",
                "functional",
                "performance",
                "compatibility",
                "breaking_change",
                "deprecation",
                "build",
                name="bug_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("reachable", sa.Boolean(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("version_confirmed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"], ["component.id"], name=op.f("fk_finding_component_id_component")
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scan.id"], name=op.f("fk_finding_scan_id_scan"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
    )
    op.create_index("ix_finding_scan", "finding", ["scan_id"], unique=False)
    op.create_table(
        "finding_citation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("bug_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bug_version_id"],
            ["bug_version.id"],
            name=op.f("fk_finding_citation_bug_version_id_bug_version"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_finding_citation_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding_citation")),
        sa.UniqueConstraint("finding_id", "bug_version_id", name="citation_is_distinct"),
    )
    # ### end Alembic commands ###

    # ---- Row-level security -------------------------------------------------------------
    for _t in _TENANT_TABLES:
        op.execute(f"ALTER TABLE {_t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {_t} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {_t}_tenant_isolation ON {_t} USING "
            "(tenant_id = NULLIF(current_setting('bugmine.tenant_id', true), '')::uuid)"
        )

    # bug_record is the exception: public and subscriber records are visible to everyone,
    # tenant-scoped ones only to their owner. Unset session tenant — the anonymous public
    # path — sees no tenant rows at all, so a handler that forgets its filter cannot leak.
    op.execute("ALTER TABLE bug_record ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE bug_record FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY bug_record_scope ON bug_record USING ("
        "privacy_scope IN ('public', 'subscriber') OR "
        "tenant_id = NULLIF(current_setting('bugmine.tenant_id', true), '')::uuid)"
    )

    op.execute("ALTER TABLE bug_version ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE bug_version FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY bug_version_via_record ON bug_version USING "
        "(EXISTS (SELECT 1 FROM bug_record r WHERE r.id = bug_version.record_id))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_citation")
    op.drop_index("ix_finding_scan", table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_scan_tenant_id"), table_name="scan")
    op.drop_table("scan")
    op.drop_index("ix_membership_user", table_name="membership")
    op.drop_table("membership")
    op.drop_index("ix_invite_token", table_name="invite")
    op.drop_index("ix_invite_tenant_email", table_name="invite")
    op.drop_table("invite")
    op.drop_index("ix_bug_version_observed", table_name="bug_version")
    op.drop_table("bug_version")
    op.drop_index("ix_api_key_tenant", table_name="api_key")
    op.drop_table("api_key")
    op.drop_table("team")
    op.drop_index("ix_job_type_state", table_name="job")
    op.drop_index(op.f("ix_job_tenant_id"), table_name="job")
    op.drop_index("ix_job_created", table_name="job")
    op.drop_table("job")
    op.drop_table("component_alias")
    op.drop_index("ix_bug_record_state", table_name="bug_record")
    op.drop_index("ix_bug_record_scope", table_name="bug_record")
    op.drop_index("ix_bug_record_retrieval", table_name="bug_record")
    op.drop_index(op.f("ix_bug_record_identity_key"), table_name="bug_record")
    op.drop_table("bug_record")
    op.drop_table("tenant")
    op.drop_table("component")
    op.drop_table("app_user")
    # ### end Alembic commands ###
    for _name in _ENUM_TYPES:
        postgresql.ENUM(name=_name).drop(op.get_bind(), checkfirst=True)
